name: NPM package

on:
  workflow_run:
    workflows: ["conan-package"]
    types:
      - completed

jobs:
  conan-recipe-version:
    name: Calculate version numbers
    uses:  ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml
    permissions:
      contents: read

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ conan-recipe-version ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@NP-637_conan_v2_wasm  # Remove this line after merge
        with:
          conan_user: ${{ secrets.CONAN_USER }}
          conan_password: ${{ secrets.CONAN_PASS }}
          conan_config_branch: "NP-637_conan_v2_wasm"  # Remove this line after merging https://github.com/Ultimaker/cura-workflows/pull/32
          install_system_dependencies: true
          repository_path: _sources

      - name: Gather/build the packages
        run: conan install --requires "${{ needs.conan-recipe-version.outputs.version_full }}" -pr:h cura_wasm.jinja --build=missing --update -of .

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ultimaker'

      - name: Publish to GitHub Packages
        run: |
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
